project/project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipe.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.IMAGE_URL, document_root=settings.IMAGE_ROOT)

project/recipe/urls.py
from django.urls import path
from . import views

app_name = 'recipe'

urlpatterns = [
    path('', views.RecipeListView.as_view(), name='recipes'),
    path('mypage/<int:user_id>', views.MypageView.as_view(), name='mypage'),
    # path('recipe_create', views.RecipeCreateView.as_view(), name='recipe_create'),
    path('recipe_create', views.RecipeCreateFormView.as_view(), name='recipe_create'),
    path('recipe/<int:recipe_id>', views.RecipeDetail.as_view(), name='recipe_detail'),
    path('recipe/edit/<int:recipe_id>', views.RecipeEditFormView.as_view(), name='recipe_edit'),
    path('test/<int:test_id>', views.get_test_response, name='test')
]

project/recipe/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)



## ユーザー情報定義
class UserManager(BaseUserManager):
    """
    ユーザー生成のためのヘルパークラス
    """

    def create_user(self, email, date_of_birth, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            date_of_birth=date_of_birth,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, date_of_birth, password):
        user = self.create_user(
            email,
            password=password,
            date_of_birth=date_of_birth,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    """
    ユーザー情報モデル
    """
    email = models.EmailField(
        verbose_name='email',
        max_length=255,
        unique=True,
    )
    date_of_birth = models.DateField()
    user_name = models.CharField(max_length=150, null=True)# ユーザの名前
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    icon = models.ImageField(upload_to='images', blank=True, null=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['date_of_birth']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    class Meta:
        db_table = "user"


class RecipeImage(models.Model):
    """
    レシピ記事の画像情報モデル
    """
    image_path = models.ImageField(upload_to='images',blank=True, null=True)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "recipe_image"
        verbose_name = "RecipeImage"

class Categorys(models.Model):
    """
    カテゴリー情報モデル
    """
    category_name = models.CharField(max_length=150)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.category_name

    class Meta:
        db_table = "categorys"
        verbose_name = "Categorys"



class Materials(models.Model):
    """
    材料情報モデル
    """
    material_name = models.CharField(max_length=150)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.material_name

    class Meta:
        db_table = "materials"
        verbose_name = "Materials"


class Recipes(models.Model):
    """
    レシピ情報モデル
    """
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True
    )
    
    category = models.ForeignKey(
        Categorys,
        on_delete=models.CASCADE
    )

    recipe_image = models.ForeignKey(
        RecipeImage,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    material = models.ManyToManyField(
        Materials,
        through="MaterialControl"
    )

    recipe_title = models.CharField(max_length=150)
    recipe_sentents = models.TextField(blank=True)
    created_sum = models.IntegerField()

    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.recipe_title

    class Meta:
        db_table = "recipes"
        verbose_name = "Recipes"


class MaterialControl(models.Model):
    """
    材料情報中間テーブルモデル
    """
    recipe = models.ForeignKey(
        Recipes,
        on_delete=models.CASCADE
    )
    material = models.ForeignKey(
        Materials,
        on_delete=models.CASCADE
    )
    amount = models.CharField(max_length=150, blank=True)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "material_control"
        verbose_name = "MaterialControl"

    
class RecipeProcessImage(models.Model):
    """
    レシピ工程画像情報モデル
    """
    image_path = models.ImageField(upload_to='images',blank=True, null=True)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "recipe_process_image"
        verbose_name = "RecipeProcessImage"

class RecipeProcess(models.Model):
    """
    レシピ工程情報モデル
    """
    recipe = models.ForeignKey(
        Recipes,
        on_delete=models.CASCADE
    )
    process_image = models.ForeignKey(
        RecipeProcessImage,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    process_order = models.IntegerField()
    process_text = models.TextField(blank=True)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "ProcessOrderNum:" + self.process_order

    class Meta:
        db_table = "recipe_process"
        verbose_name = "RecipeProcess"
    

class Favorites(models.Model):
    """
    お気に入り管理モデル
    """
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    recipe = models.ForeignKey(
        Recipes,
        on_delete=models.CASCADE
    )
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "favorites"
        verbose_name = "Favorites"

project/recipe/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from .models import User, Materials, Categorys
import logging
# from .views import RecipeEditFormView

class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'date_of_birth')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'date_of_birth',
                  'is_active', 'is_admin')

    def clean_password(self):
        return self.initial["password"]


# レシピ投稿新規作成フォーム
class RecipeCreateForm(forms.Form):
    recipe_title = forms.CharField(label='タイトル', required=True)
    recipe_sentence = forms.CharField(label='説明文', \
                                      widget=forms.Textarea, \
                                      required=True)

    category_id_choice = forms.ChoiceField(
        label='カテゴリー', 
        required=True
    )

    material_id_multi_choice = forms.MultipleChoiceField(
        label='材料',
        widget=forms.CheckboxSelectMultiple()
    )

    recipe_image = forms.ImageField(
        label="レシピ画像",
        required=True
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        category_list = [(0, 'カテゴリーを選択')]
        for category in Categorys.objects.all():
            category_list.append((category.id, category.category_name))
        self.fields['category_id_choice'].choices = category_list

        self.fields['material_id_multi_choice'].choices = \
            lambda: [(material.id, material.material_name) for material in Materials.objects.all()]

    def clean_category_id_choice(self):
        data = self.cleaned_data['category_id_choice']
        print('validate category',data, type(data))
        if data == '0':
            print('raise error')
            raise forms.ValidationError("いずれかのカテゴリーを選択してください。")
        return data

    def clean_recipe_image(self):
        data = self.cleaned_data['recipe_image']
        # print('validate image', data, type(data))

        return data

# レシピ編集フォーム
class RecipeUpdateForm(RecipeCreateForm):

    def __init__(self, *args, **kwargs):
        #viewからの値を取得
        title = kwargs.pop('recipe_title')
        recipe_sentence = kwargs.pop('recipe_sentence')
        recipe_image = kwargs.pop('recipe_image')
        category_id_choice = kwargs.pop('category_id_choice')
        material_id_multi_choice = kwargs.pop('material_id_multi_choice')

        # 初期化
        super().__init__(*args, **kwargs)

        logger = logging.getLogger("consol")
        # 値を設定
        self.fields['recipe_title'].initial = title
        self.fields['recipe_sentence'].initial = recipe_sentence
        self.fields['category_id_choice'].initial = category_id_choice
        self.fields['material_id_multi_choice'].initial = material_id_multi_choice
        self.fields['recipe_image'].initial = '/' + recipe_image.image_path.url
        self.fields['recipe_image'].required = True

project/recipe/templates/recipe/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport"
    content="width=device-width, initial-scale=1.0, user-scalable=1.0, minimum-scale=1.0, maximum-scale=1.0" />
  <meta name="description" content="ページの内容を表す文章" />
  <link rel="canonical" href="正規化するURL" /><!-- URLの正規化 -->
  <title>{% block title %}{% endblock  %}</title>
  <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
</head>
<body>
  <header>
    <h1><a href="{% url 'recipe:recipes'%}">Recipe Sharing</a></h1>
    <div class="user-account-area">
      <ul>
        <li><a href="{% url 'recipe:mypage' 1 %}">Hikaru</a></li>
        <li><a href="#">LogOut</a></li>
      </ul>
    </div>
  </header>

  <div class="container preload">
      {% block content1%}
      {% endblock %}
  </div>

  <footer>
    <p>&copy;Hikaru All Right Reserved 2020</p>
  </footer>
    
    <script src="{% static 'recipe/js/base.bundle.js' %}"></script>
    
    {% block js %}
    {% endblock %}
</body>
</html>

project/recipe/templates/recipe/mypage.html
{% extends './base.html' %}
{% load static %}

{% block title %}
マイページ
{% endblock  %}


{% block content1 %}
    <div class="profile-area">
        <div class="icon-area">
            <img src="/{{user.icon.url }}" alt="user-image">
        </div>
        <div class="profile">
            <div class="user-info">
                <span class="user">ユーザー</span>
                <p class="user-name">{{user.user_name}}</p>
            </div>
            <p class="create-recipe-link"><a href="{% url 'recipe:recipe_create' %}">レシピ投稿</a></p>
        </div>
        <div class="action-area">
            <div class="count-area count-left-area">
                <span>レシピ投稿数</span>
                <p>0</p>
            </div>
            <div class="count-area">
                <span>お気に入り数</span>
                <p>0</p>
            </div>
            <div class="count-area">
                <span>総つくった！数</span>
                <p>0</p>
            </div>
        </div>
    </div>
    <div class="recipe-list-area">
        <h3>{{user.user_name}}さんの投稿記事一覧</h3>
        <hr>
        <div class="recipe-list">
            <div class="recipe-article-list-area">
                {% for recipe in recipe_list %}
                <article class="recipe-article">
                    <img class="recipe_article_image" src="/{{ recipe.recipe_image.image_path.url }}"
                        alt="recipe_image">
                    <div class="recipe-article-content">
                        <h3>{{ recipe.recipe_title }}</h3>
                        <p><span>{{recipe.category_name}}</span> by{{ recipe.user_name }}</p>
                        <p class="recipe_sentents">{{ recipe.recipe_sentents}}</p>
                        <p class="material_info_str">材料：{{ recipe.material_info_str }}</p>
                        <div class="link-area">
                            <a class="link-a-tag link-orange" href="{% url 'recipe:recipe_detail' recipe.recipe_id %}">詳細へ</a>
                            <a class="link-a-tag link-red" href="{% url 'recipe:recipe_edit' recipe.recipe_id %}">編集・削除</a>
                        </div>
                    </div>
                </article>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock  %}


{% block js %}
<script src={% static 'recipe/js/mypage.bundle.js' %}></script>
{% endblock %}

project/recipe/templates/recipe/recipe_create.html
{% extends './base.html' %}
{% load static %}

{% block title %}
レシピ投稿
{% endblock  %}


{% block content1 %}
    <div class="create-recipe-form-area">
        {% if is_edit %}
        <h1 id="header-title-recipe-create-page">レシピ編集</h1>
        {% else %}
        <h1 id="header-title-recipe-create-page">レシピ投稿</h1>
        {% endif %}
        <hr>
        <form action="{% url 'recipe:recipe_create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="create-form form-recipe-title">
                <label for="id_recipe_title">タイトル</label>
                {{ form.recipe_title }}
                <div class="form-error-area">
                    {% if form.recipe_title.errors %}
                        {% for error in form.recipe_title.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="create-form recipe-image-area">
                <label for="id_recipe_image">レシピ紹介画像</label>
                {{ form.recipe_image }}
                {% for error in form.recipe_image.errors %}
                <p>{{ error }}</p>
                {% endfor %}
            </div>
            <div class="create-form form-recipe-sentence">
                <label for="id_recipe_sentence">レシピ紹介文</label>
                {{ form.recipe_sentence}}
                <div class="form-error-area">
                    {% if form.recipe_sentence.errors %}
                        {% for error in form.recipe_sentence.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="create-form form-category-choice">
                <label for="id_category_id_choice">カテゴリー</label>
                {{ form.category_id_choice}}
                <div class="form-error-area">
                    {% if form.category_id_choice.errors %}
                        {% for error in form.category_id_choice.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="create-form form-material-choice">
                <label for="id_material_id_multi_choice">材料</label>
                {{ form.material_id_multi_choice }}
                <div class="form-error-area">
                    {% if form.material_id_multi_choice.errors %}
                        {% for error in form.material_id_multi_choice.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="submit-button-area create-form">
                <input type="submit" value="保存">
            </div>
        </form>
    </div>
{% endblock  %}

{% block js %}
<script src={% static 'recipe/js/recipe_create.bundle.js' %}></script>
{% endblock %}

project/recipe/templates/recipe/recipe_detail.html
{% extends './base.html' %}
{% load static %}

{% block title %}
レシピ詳細
{% endblock  %}


{% block content1 %}

<div class="recipe-detail">
    <h3><span>レシピ名</span> {{ detail.recipe_title }}</h3>
    <div class="action-area">
        <button class="button-system button-favorite">★{{detail.favorite_sum}} Favorite!!</button>
        <button class="button-system button-created">つくった！{{detail.created_sum}}</button>
        <a class="user-link" href="#">by{{detail.user_name}}</a>
    </div>
    <div class="recipe-detail-area">
        <img src="/{{ detail.recipe_image.image_path }}" alt="recipe_image">
        <div class="recipe-introduce">
            <p class="sentence">{{ detail.recipe_sentents }}</p>
            <p class="category-name"><span>{{detail.category_name}}</span></p>
            <div class="material-list">
                <p>材料</p>
                <ul>
                    {% for material in detail.material %}
                    <li>{{material.material_name}}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock  %}


{% block js %}
<script src={% static 'recipe/js/recipe_detail.bundle.js' %}></script>
{% endblock %}

project/recipe/templates/recipe/recipe_edit.html
{% extends './base.html' %}
{% load static %}

{% block title %}
レシピ編集
{% endblock  %}

{% block content1 %}
    <div class="create-recipe-form-area">
        <h1 id="header-title-recipe-create-page">レシピ編集</h1>
        <hr>
        <form action="{% url 'recipe:recipe_edit' edit_recipe_id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="create-form form-recipe-title">
                <label for="id_recipe_title">タイトル</label>
                {{ form.recipe_title }}
                <div class="form-error-area">
                    {% if form.recipe_title.errors %}
                        {% for error in form.recipe_title.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="create-form recipe-image-area">
                <label for="id_recipe_image">レシピ紹介画像</label>
                {{ form.recipe_image }}
                {% for error in form.recipe_image.errors %}
                <p>{{ error }}</p>
                {% endfor %}
            </div>
            <div class="create-form form-recipe-sentence">
                <label for="id_recipe_sentence">レシピ紹介文</label>
                {{ form.recipe_sentence}}
                <div class="form-error-area">
                    {% if form.recipe_sentence.errors %}
                        {% for error in form.recipe_sentence.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="create-form form-category-choice">
                <label for="id_category_id_choice">カテゴリー</label>
                {{ form.category_id_choice}}
                <div class="form-error-area">
                    {% if form.category_id_choice.errors %}
                        {% for error in form.category_id_choice.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="create-form form-material-choice">
                <label for="id_material_id_multi_choice">材料</label>
                {{ form.material_id_multi_choice }}
                <div class="form-error-area">
                    {% if form.material_id_multi_choice.errors %}
                        {% for error in form.material_id_multi_choice.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>

            <div class="submit-button-area create-form">
                <input type="submit" value="変更">
            </div>
        </form>
    </div>
{% endblock  %}

{% block js %}
<script src={% static 'recipe/js/recipe_create.bundle.js' %}></script>
{% endblock %}

project/recipe/templates/recipe/recipe_list.html
{% extends './base.html' %}
{% load static %}

{% block title %}
レシピ共有アプリケーション
{% endblock  %}

{% block content1 %}

<!-- 検索フォームエリア -->
<div class="search-area">
    <div class="inputed-data-area" style="display:none">
        {% if parameter %}
            {% if parameter.title %}
                <p id="inputed-title">{{parameter.title}}</p>
            {% endif %}
            {% if parameter.categorys %}
                <p id="inputed-categorys">{{parameter.categorys}}</p>
            {% endif %}
            {% if parameter.materials %}
                <p id="inputed-materials">{{parameter.materials}}</p>
            {% endif %}
        {% endif %}
    </div>
    <h3 class="search-title title-sub">検索条件</h3>
    <hr>
    <div class="search-form-ara">
        <label class="form-label" for="title-recipe">タイトル</label>
        <input class="form-input" type="text" id="title-recipe" placeholder="タイトルで検索">
        <label for="category-recipe">カテゴリー</label>
        <select class="form-input" name="category" id="category-recipe">
            <option value="0">カテゴリーを選択してください</option>
            {% for category in search_form_list.categorys %}
                <option value="{{ category.id }}">{{ category.category_name}}</option>
            {% endfor %}
        </select>
        <label for="material-recipe">材料</label>
        <div class="form-input" id="material-check-box">
            {% for material in search_form_list.materials %}
                <input type="checkbox" class="material-item" name="material" value="{{ material.id }}">{{material.material_name}}<br>  
            {% endfor %}
        </div>
        <form id="search-recipe-form">
            <p class='url-pattern'>
                {% url 'recipe:recipes' %}
            </p>
            <input type="hidden" name="title">
            <input type="hidden" name="categorys">
            <input type="hidden" name="materials">
        </form>
        <div class="submit-form">
            <button class="button-system search-button">検索</button>
        </div>
    </div>
</div>

<!-- 投稿レシピ一覧エリア -->
<div class="recipe-list-area">
    <h3 class="recipe-list-title title-sub">レシピ一覧</h3>
    <hr>
    <div class="recipe-article-list-area">
        {% for recipe in recipe_list %}
            <article class="recipe-article">
                <a href="{% url 'recipe:recipe_detail' recipe.recipe_id %}" style="display:none;"></a>
                <img class="recipe_article_image" src="/{{ recipe.recipe_image.image_path.url }}" alt="recipe_image">
                <div class="recipe-article-content">
                    <h3>{{ recipe.recipe_title }}</h3>
                    <p><span>{{recipe.category_name}}</span> by{{ recipe.user_name }}</p>
                    <p class="recipe_sentents">{{ recipe.recipe_sentents}}</p>
                    <p class="material_info_str">材料：{{ recipe.material_info_str }}</p>
                    <button class="button-system button-favorite">★{{recipe.favorite_sum}} Favorite!!</button>
                </div>
            </article>
        {% endfor %}
    </div>
</div>
{% endblock  %}


{% block js %}
<script src={% static 'recipe/js/recipes.bundle.js' %}></script>
{% endblock %}